### ISSUE TITLE
togglable side bar: full text

### ISSUE THREAD

**Issue by ktakahata** [ktakahata/grainger#13]
Full text currently has a working side bar, but the navigation requires adding headers that aren't already in the text (for Front Matter and End Matter) and having Preface and Books I, II, III, IV look like headers rather than plain text. Is there a way to hide where the toc navigates to so that we only have what's actually in Grainger's text on the page?

**Comment by elotroalex** [comment]
So what do we have actually in Grainger's text that you want to have in the side bar. Give me a bullet point list if you can.

**Comment by ktakahata** [comment]
Front cover
Preface
Book I
Book II
Book III
Book IV
Index

I think Julie and Cristobal would prefer the current categories. If it’s
not possible, we could do the above ones.

**Comment by elotroalex** [comment]
@ktakahata I just added the content of the sidebar. Since you know better than I do what text is or is not in the original, I will leave it to you to create the right html span elements with the necessary IDs for you to be able to jump to the proper place on the page. Here's an example:

`<span id="#book-i"></span>`

Place this to wrap existing text or put them in an empty spot in between text. It is up to you. The page will jump to the spot where you put it when you click the relevant menu item on the sidebar TOC.

**Comment by ktakahata** [comment]
Added ids to preface, Books I-IV, and index. Deleted all header designations

**Comment by elotroalex** [comment]
Is it working now?
